name: NDS

on: [push, pull_request]

jobs:
  build:
    name: DevkitARM build
    runs-on: ubuntu-latest
    container: 
      image: devkitpro/devkitarm:latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Make
      run: |
        make clean
        make

    - name: Prepare dist folder
      run: |
        mkdir dist
        mv ./ao-nds.nds ./dist/
        mv ./fat ./dist/
        
    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: NDS ROM
        path: ./dist

  converter:
    name: Converter tool
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install Python 3
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install pip dependencies
      run: pip install apng Pillow requests joblib pyinstaller

    - name: Build exe with pyinstaller
      run: |
        cd converter
        pyinstaller main.spec

    - name: Copy files to dist
      shell: cmd
      run: |
        cd converter
        copy libstdc++-6.dll libgcc_s_sjlj-1.dll FreeImage.dll grit.exe dist

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: Converter tool
        path: ./converter/dist
        
